<Project>
	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	</PropertyGroup>

	<ItemGroup>
		<PackageVersion Include="Zongsoft.Core" Version="7.59.1" />
		<PackageVersion Include="Zongsoft.CodeAnalysis" Version="1.2.1" />
	</ItemGroup>

	<ItemGroup>
		<PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
		<PackageVersion Include="xunit.v3" Version="3.2.2" />
		<PackageVersion Include="xunit.v3.core" Version="3.2.2" />
		<PackageVersion Include="xunit.v3.assert" Version="3.2.2" />
		<PackageVersion Include="xunit.analyzers" Version="1.27.0" />
		<PackageVersion Include="xunit.v3.runner.msbuild" Version="3.2.2" />
		<PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
	</ItemGroup>
</Project>
