//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zongsoft.Regular.Properties {
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zongsoft.Regular.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 An error occurred:{0}{1} 的本地化字符串。
        /// </summary>
        internal static string Error_Message {
            get {
                return ResourceManager.GetString("Error.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Information 的本地化字符串。
        /// </summary>
        internal static string Information_Title {
            get {
                return ResourceManager.GetString("Information.Title", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Please enter the input text. 的本地化字符串。
        /// </summary>
        internal static string InputRequired_Message {
            get {
                return ResourceManager.GetString("InputRequired.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Create a new file?{0}{0}Unsaved changes to the current pattern will be lost. Save them first if needed. 的本地化字符串。
        /// </summary>
        internal static string NewFile_Confirmation {
            get {
                return ResourceManager.GetString("NewFile.Confirmation", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 New file 的本地化字符串。
        /// </summary>
        internal static string NewFile_Title {
            get {
                return ResourceManager.GetString("NewFile.Title", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Regular expression options:{0}{1}{0}{0}This version does not support configuring options. Please check for updates. 的本地化字符串。
        /// </summary>
        internal static string Options_Message {
            get {
                return ResourceManager.GetString("Options.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Options 的本地化字符串。
        /// </summary>
        internal static string Options_Title {
            get {
                return ResourceManager.GetString("Options.Title", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Please enter a regular expression. 的本地化字符串。
        /// </summary>
        internal static string PatternRequired_Message {
            get {
                return ResourceManager.GetString("PatternRequired.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Text files (*.txt)|*.txt 的本地化字符串。
        /// </summary>
        internal static string TextFile_Filter {
            get {
                return ResourceManager.GetString("TextFile.Filter", resourceCulture);
            }
        }
    }
}
