using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Formats.Tar;
using System.IO.Compression;
using System.Collections.Generic;

using Xunit;

using Zongsoft.Components;
using Zongsoft.Tools.Containerizer.Protocol;

namespace Zongsoft.Tools.Containerizer.Tests;

public sealed class ContainerManifestTests : IDisposable
{
	private readonly string _root = Path.Combine(Path.GetTempPath(), "containerizer-tests-" + Guid.NewGuid().ToString("N"));
	public ContainerManifestTests() => Directory.CreateDirectory(_root);
	public void Dispose() => Directory.Delete(_root, true);

	[Theory]
	[InlineData(2026, 10, 4, "26.10.4")]
	[InlineData(2126, 1, 2, "126.1.2")]
	[InlineData(2000, 2, 9, "0.2.9")]
	public void AutomaticDateVersionUsesTheLastThreeYearDigits(int year, int month, int day, string expected) => Assert.Equal(expected, ContainerManifest.DateVersion(new DateTime(year, month, day)));

	[Theory]
	[InlineData("name=a\nName=b\n[redis]\n")]
	[InlineData("name=a\naddress=127.0.0.1\n[redis]\n")]
	[InlineData("name=a\nmode=offline\n[redis]\n")]
	[InlineData("name=a\n[node redis]\n")]
	[InlineData("name=a\n[redis]\n\nenvironment!X=1\nenvironment!x=2")]
	[InlineData("name=a\nmigration#0=file\n[redis]\n")]
	[InlineData("name=a\nmigration#1=a\nmigration#01=b\n[redis]\n")]
	[InlineData("name=a\nmigration=directory\n[redis]\n")]
	public void RejectsInvalidDeclarations(string text)
	{
		var path = this.Write("input.container", text);
		Assert.Throws<ContainerizationException>(() => ContainerManifest.Read(path));
	}

	[Theory]
	[InlineData("1.0")]
	[InlineData("1.0.0")]
	[InlineData("1.2.3.4")]
	[InlineData("65535.65535.65535.65535")]
	public void NumericReleaseVersionsPreserveTheirInputText(string version)
	{
		var manifest = ContainerManifest.From(Context("redis", "--name:example", "--distribution:debian", "--source:" + _root, "--version:" + version));
		Assert.Equal(version, manifest["version"]);
		var path = new DeliveryBuilder(new ProcessRunner()).Plan(manifest);
		Assert.Equal(version, ContainerManifest.Read(path)["version"]);
		var assembly = typeof(ContainerManifest).Assembly.GetName();
		Assert.StartsWith($"# Generated by {assembly.Name}@{assembly.Version.ToString(assembly.Version.Revision > 0 ? 4 : 3)}\r\n\r\n", File.ReadAllText(path), StringComparison.Ordinal);
	}

	[Theory]
	[InlineData("0.0")]
	[InlineData("65536.0")]
	[InlineData("1.0.0.65536")]
	[InlineData("1.0.0-preview")]
	public void ReleaseVersionMustBeANonzeroCoreNumber(string version)
	{
		var error = Assert.Throws<ContainerizationException>(() => ContainerManifest.From(Context("redis", "--name:example", "--distribution:debian", "--source:" + _root, "--version:" + version)));
		Assert.Equal(2, error.Code);
	}

	[Fact]
	public void ImportsCannotSilentlyOverride()
	{
		this.Write("child.container", "name=other\n[redis]\n\n");
		var path = this.Write("main.container", "name=example\n#@import child.container\n");
		Assert.Throws<ContainerizationException>(() => ContainerManifest.Read(path));
	}

	[Theory]
	[InlineData("image", "redis")]
	[InlineData("version", "8.4")]
	[InlineData("name", "redis")]
	[InlineData("image!service", "redis")]
	[InlineData("platform", "linux")]
	[InlineData("architecture", "x64")]
	[InlineData("mode", "offline")]
	public void RemovedComponentFieldsAreRejected(string key, string value)
	{
		var path = this.Write("removed.container", "name=example\n[redis]\n" + key + "=" + value);
		Assert.Throws<ContainerizationException>(() => ContainerManifest.Read(path));
	}

	[Theory]
	[MemberData(nameof(ContainerEngineTests.InvalidDigests), MemberType = typeof(ContainerEngineTests))]
	public void ManifestRejectsInvalidImageDigests(string digest)
	{
		var manifest = ContainerManifest.From(Context("redis", "--name:example", "--distribution:debian", "--source:" + _root, "--version:1.0"));
		manifest.Components[0]["digest"] = digest;
		var exception = Assert.Throws<ContainerizationException>(() => manifest.Validate());
		Assert.Equal(2, exception.Code);
	}

	[Fact]
	public void AutomaticVersionsCheckBothFinalFilesAndIncludeArchitecture()
	{
		var date = ContainerManifest.DateVersion(DateTime.Today);
		this.Write("example@" + date + "-x64.container", "occupied");
		this.Write("example@" + date + ".1-x64.tar.gz", "occupied");
		var manifest = ContainerManifest.From(Context("redis", "--name:example", "--distribution:debian", "--source:" + _root));
		Assert.Equal(date + ".2", manifest["version"]);
		Assert.Equal("example@" + date + ".2-x64", manifest.ReleaseName);
		Assert.Throws<ContainerizationException>(() => ContainerManifest.From(Context("redis", "--name:example", "--distribution:debian", "--source:" + _root, "--version:" + date)));
		var arm = ContainerManifest.From(Context("redis", "--name:example", "--distribution:debian", "--architecture:arm64", "--source:" + _root, "--version:" + date));
		Assert.Equal("example@" + date + "-arm64", arm.ReleaseName);
	}

	[Fact]
	public void MigrationKeysSortNumericallyAndRootCanResume()
	{
		var path = this.Write("input.container", "name=example\nmigration#10=ten\nmigration#2=two\n[redis]\n\n[]\ntag=data\n");
		var manifest = ContainerManifest.Read(path);
		Assert.Equal(["two", "ten"], manifest.Migrations);
		Assert.Equal("data", manifest["tag"]);
	}

	[Fact]
	public void SettingsUseConnectionSettingsSemantics()
	{
		var component = new ContainerManifest.Component();
		component["settings"] = "a=first;A=last;empty=;x=a=b;";
		Assert.Equal("last", component.Settings["a"]);
		Assert.Equal("", component.Settings["empty"]);
		Assert.Equal("a=b", component.Settings["x"]);
	}

	[Theory]
	[InlineData("debian", "debian@13")]
	[InlineData("debian@12", "debian@12")]
	[InlineData("redhat", "rhel@9")]
	[InlineData("ubuntu", "ubuntu@22.04")]
	public void DistributionDefaultsAreFixed(string input, string expected) => Assert.Equal(expected, Distribution.Normalize(input));

	[Theory]
	[InlineData("debian@11")]
	[InlineData("debian@14")]
	[InlineData("rocky@8")]
	[InlineData("ubuntu@latest")]
	public void UnvalidatedDistributionProfilesFail(string input) => Assert.Throws<ContainerizationException>(() => Distribution.Normalize(input));

	[Fact]
	public void ExplicitOverridesPreserveSourceAndPackageSelections()
	{
		var source = Path.Combine(_root, "source");
		Directory.CreateDirectory(source);
		this.Write("source/.env", "version=99.0\narchitecture=arm64\noutput=wrong\n");
		var input = this.Write("input.container", "name=example\nsource=source\nversion=1.0\ndistribution=debian\narchitecture=x64\noutput=out\n[redis]\n\n");
		var result = ContainerManifest.From(Context(input, "--version:2.0"));
		Assert.Equal("2.0", result["version"]);
		Assert.Equal("x64", result["architecture"]);
		Assert.Equal(Path.Combine(source, "out"), result["output"]);
		Assert.Equal(source, result["source"]);
		Assert.Contains("version=1.0", File.ReadAllText(input), StringComparison.Ordinal);
	}

	[Fact]
	public void BuiltinWinsOverSameNamedDirectory()
	{
		Directory.CreateDirectory(Path.Combine(_root, "redis"));
		var manifest = ContainerManifest.From(Context("redis", "--name:example", "--distribution:debian", "--source:" + _root));
		Assert.Equal("redis", Assert.Single(manifest.Components).Name);
		Assert.Equal(_root, manifest["output"]);
		Assert.Throws<ContainerizationException>(() => ContainerManifest.From(Context("./redis", "--name:example", "--distribution:debian", "--source:" + _root)));
	}

	[Fact]
	public void SourceRelativePathsAndSavedManifestRoundTrip()
	{
		var source = Path.Combine(_root, "source");
		Directory.CreateDirectory(source);
		var manifest = ContainerManifest.From(Context("redis", "--name:example", "--distribution:debian", "--source:" + source, "--output:../delivery", "--version:1.0"));
		manifest.Components[0]["digest"] = "sha256:" + new string('a', 64);
		manifest.Components[0].Values.Remove("version");
		this.Save(manifest);
		var path = Path.Combine(_root, "delivery", "example@1.0-x64.container");
		var original = File.ReadAllBytes(path);
		Assert.Equal(Path.GetRelativePath(manifest["output"], source), ContainerManifest.Read(path)["source"]);
		Assert.Equal(Path.GetRelativePath(source, manifest["output"]), ContainerManifest.Read(path)["output"]);
		var restored = ContainerManifest.From(Context(path));
		Assert.Equal(source, restored["source"]);
		this.Save(restored);
		Assert.Equal(original, File.ReadAllBytes(path));
	}

	[Fact]
	public void TarPackageUsesMetadataInsteadOfFilename()
	{
		var path = this.Tar("renamed.tar.gz", "example.web", "arm64");
		var package = PackageReader.Read(path);
		Assert.Equal("example.web", package.Name);
		Assert.Equal("arm64", package.Architecture);
		File.Delete(path[..^7] + ".sh");
		Assert.Throws<ContainerizationException>(() => PackageReader.Read(path));
	}

	[Fact]
	public void DirectoryLevelPrecedesFormatAndNoLatestGuessing()
	{
		var first = this.Tar("example@1.0.tar.gz", "example", "x64");
		this.Tar(".packages/example@2.0.tar.gz", "example", "x64");
		Assert.Equal(first, PackageReader.Select(_root, "example", "debian@13", "x64"));
		this.Tar("example@3.0.tar.gz", "example", "x64");
		Assert.Throws<ContainerizationException>(() => PackageReader.Select(_root, "example", "debian@13", "x64"));
	}

	[Theory]
	[InlineData(true)]
	[InlineData(false)]
	public void ApplicationSelectionIgnoresCompanionFilesOnReplay(bool directory)
	{
		var package = this.Tar("app/.packages/example@1.0.tar.gz", "example", "x64");
		var input = directory ? Path.Combine(_root, "app") : package;
		this.Write((directory ? "app/" : "app/.packages/") + "container.template", "not a valid template; must never be read");
		var manifest = ContainerManifest.From(Context(input, "--name:example", "--distribution:debian", "--source:" + _root, "--output:delivery", "--version:1.0"));
		Assert.Null(Assert.Single(manifest.Components)["template"]);
		this.Save(manifest);
		var replay = ContainerManifest.From(Context(Path.Combine(_root, "delivery", "example@1.0-x64.container")));
		var component = Assert.Single(replay.Components);
		Assert.Null(component["template"]);
		Assert.Null(ServiceBuildContext.FromApplication(component, replay).Plan.Template);
		component["template"] = "nonexistent.template";
		Assert.Equal(2, Assert.Throws<ContainerizationException>(() => replay.Validate()).Code);
		Assert.Equal(2, Assert.Throws<ContainerizationException>(() => new TemplateCatalog().Read(component, replay)).Code);
	}

	[Fact]
	public void MigrationSelectionRejectsDuplicateVersionsWithoutReadingArchive()
	{
		var first = this.Write("example(migrate)@1.0_linux-x64.tar.gz", "deliberately not an archive");
		this.Write("example(migrate)@1.0_linux-x64.sh", "never executed");
		MigrationInput.Validate([first], "x64");
		Assert.Equal("1.0", MigrationInput.Parse(first).VersionText);
		var equivalent = this.Write("example(migrate)@1.0.0_linux-x64.tar.gz", "not unpacked");
		this.Write("example(migrate)@1.0.0_linux-x64.sh", "never executed");
		Assert.Throws<ContainerizationException>(() => MigrationInput.Validate([first, equivalent], "x64"));
		var second = this.Write("example-other(migrate)@1.0_linux-x64.tar.gz", "not unpacked");
		this.Write("example-other(migrate)@1.0_linux-x64.sh", "never executed");
		Assert.Throws<ContainerizationException>(() => MigrationInput.Validate([first, second], "x64"));
		Assert.Throws<ContainerizationException>(() => MigrationInput.Validate([first], "arm64"));
	}





	[Fact]
	public void AllBuiltinTemplatesParseWithoutUnknownProtocolFields()
	{
		var manifest = new ContainerManifest();
		manifest["source"] = _root;
		manifest["architecture"] = "x64";
		manifest["name"] = "example";

		foreach(var path in Directory.EnumerateFiles(Path.GetDirectoryName(TemplateCatalog.Find("redis.template")), "*.template"))
		{
			var name = Path.GetFileNameWithoutExtension(path);
			var component = new ContainerManifest.Component { Name = name };
			component["template"] = name;
			var source = new TemplateCatalog().Read(component, manifest);
			Assert.Equal(name, source.Plan.Id);
			Assert.NotEmpty(source.Plan.Health.Test);
			Assert.NotEmpty(source.SourceImage);
		}
	}

	[Fact]
	public void MysqlRootPasswordUsesSourceVariablesAndExplicitOverrides()
	{
		this.Write(".env", "[mysql]\nroot_password=$(test_password)\n[]\ntest_password=example-only\n");
		var manifest = ContainerManifest.From(Context("mysql", "--name:example", "--distribution:debian", "--source:" + _root));
		var component = Assert.Single(manifest.Components);
		var catalog = new TemplateCatalog();
		var source = catalog.Read(component, manifest);
		Assert.Equal("example-only", source.Environment["MYSQL_ROOT_PASSWORD"]);
		var mount = Assert.Single(source.Plan.Mounts);
		Assert.Equal("/var/lib/containerizer/data/example/mysql", mount.Source);
		Assert.Equal("/var/lib/mysql", mount.Target);
		Assert.Empty(source.MissingSettings);

		manifest.Variables["mysql_root_password"] = "$(unused_missing_variable)";
		component["settings"] = "root-password=explicit-setting";
		source = catalog.Read(component, manifest);
		Assert.Equal("explicit-setting", source.Environment["MYSQL_ROOT_PASSWORD"]);

		component["environment!MYSQL_ROOT_PASSWORD"] = "explicit-environment";
		Assert.Throws<ContainerizationException>(() => catalog.Read(component, manifest));
	}

	[Fact]
	public void MysqlMissingSourceVariableStillRequiresPasswordAndAllowsExplicitEnvironment()
	{
		var manifest = ContainerManifest.From(Context("mysql", "--name:example", "--distribution:debian", "--source:" + _root));
		manifest.Variables.Remove("mysql_root_password");
		var component = Assert.Single(manifest.Components);
		var catalog = new TemplateCatalog();
		var source = catalog.Read(component, manifest);
		Assert.Contains("root-password", source.MissingSettings);
		Assert.False(source.Environment.ContainsKey("MYSQL_ROOT_PASSWORD"));

		component["environment!MYSQL_ROOT_PASSWORD"] = "explicit-environment";
		source = catalog.Read(component, manifest);
		Assert.Equal("explicit-environment", source.Environment["MYSQL_ROOT_PASSWORD"]);
	}

	[Fact]
	public void TemplateVariableBindingPreservesDefaultAndEmptyValues()
	{
		this.Write("custom.template", "version=1\nimage=docker.io/library/mysql\n[settings root-password]\nenvironment=MYSQL_ROOT_PASSWORD\nvariable=custom_password\ndefault=fallback\nrequired=true\n");
		var manifest = ContainerManifest.From(Context("mysql", "--name:example", "--distribution:debian", "--source:" + _root));
		manifest.Variables.Remove("custom_password");
		var component = Assert.Single(manifest.Components);
		component["template"] = "custom.template";
		var catalog = new TemplateCatalog();
		Assert.Equal("fallback", catalog.Read(component, manifest).Environment["MYSQL_ROOT_PASSWORD"]);

		manifest.Variables["custom_password"] = "";
		Assert.Equal("", catalog.Read(component, manifest).Environment["MYSQL_ROOT_PASSWORD"]);

		manifest.Variables["custom_password"] = "referenced";
		Assert.Equal("referenced", catalog.Read(component, manifest).Environment["MYSQL_ROOT_PASSWORD"]);
	}

	[Fact]
	public void TemplateValuesUseSourceVariablesAndPreserveArgumentBoundaries()
	{
		this.Write(".env", "[build]\nbind=127.0.0.1\nport=16379\nmessage=two \"quotes\" C:\\tmp\n");
		var configuration = this.Write("templates/config/redis.conf", "protected-mode yes\n");
		this.Write("templates/redis.template", "version=1\nimage=docker.io/library/redis\nplatforms=x64\nCommand=[\"redis-server\",\"$(build_message)\",\"%build_port%\",\"$$(RUNTIME_COMMAND)\"]\nhealth=[\"CMD-SHELL\",\"echo $$TOKEN\"]\n[environment]\nTOKEN=$(build_message)\nRELEASE=$(name)@$(version)\n[ports]\ndefault=$(build_bind):%build_port%:6379\n[data]\ndata=$(data_path)\n[configuration]\n/etc/redis.conf=$(config_path)\n[settings message]\nenvironment=MESSAGE\ndefault=$(build_message)\n");
		var input = this.Write("input.container", "name=example\nversion=1.0\ndistribution=debian\n[redis]\n\ntemplate=templates/redis.template\nenvironment!TOKEN=explicit\n");
		var manifest = ContainerManifest.From(Context(input, "--source:" + _root));
		manifest.Variables["data_path"] = "/cache";
		manifest.Variables["config_path"] = "config/redis.conf";
		var source = new TemplateCatalog().Read(Assert.Single(manifest.Components), manifest);
		Assert.Equal(["redis-server", "two \"quotes\" C:\\tmp", "16379", "$(RUNTIME_COMMAND)"], source.Plan.Command);
		Assert.Equal(["CMD-SHELL", "echo $TOKEN"], source.Plan.Health.Test);
		Assert.Equal("explicit", source.Environment["TOKEN"]);
		Assert.Equal("two \"quotes\" C:\\tmp", source.Environment["MESSAGE"]);
		Assert.Equal("example@1.0", source.Environment["RELEASE"]);
		Assert.Equal(16379, Assert.Single(source.Plan.Ports).Host);
		Assert.Equal("/cache", Assert.Single(source.Plan.Mounts).Target);
		Assert.Equal("/var/lib/containerizer/data/example/redis", Assert.Single(source.Plan.Mounts).Source);
		Assert.Equal(Path.GetFullPath(configuration), source.Configuration["/etc/redis.conf"]);
	}

	[Theory]
	[InlineData("$(missing)")]
	[InlineData("%missing%")]
	[InlineData("$(loop)")]
	public void TemplatesRejectUnresolvedOrCyclicVariables(string value)
	{
		this.Write(".env", "loop=$(loop)\n");
		this.Write("custom.template", "version=1\nimage=docker.io/library/redis\n[environment]\nVALUE=" + value + "\n");
		var input = this.Write("input.container", "name=example\ndistribution=debian\n[redis]\n\ntemplate=custom.template\n");
		var manifest = ContainerManifest.From(Context(input, "--source:" + _root));
		Assert.Throws<ContainerizationException>(() => new TemplateCatalog().Read(Assert.Single(manifest.Components), manifest));
	}


	private void Save(ContainerManifest manifest)
	{
		var directory = Path.Combine(_root, Guid.NewGuid().ToString("N"));
		Directory.CreateDirectory(directory);
		var prepared = manifest.Prepare(directory);
		Directory.CreateDirectory(manifest["output"]);

		if(!File.Exists(manifest.ManifestPath))
			File.Copy(prepared, manifest.ManifestPath);
		else
			Assert.Equal(File.ReadAllBytes(manifest.ManifestPath), File.ReadAllBytes(prepared));
	}

	private string Write(string relative, string content)
	{
		var path = Path.Combine(_root, relative);
		Directory.CreateDirectory(Path.GetDirectoryName(path));
		File.WriteAllText(path, content);
		return path;
	}
	private string Tar(string relative, string name, string architecture)
	{
		var path = this.Write(relative, "");

		using(var output = File.Create(path))
		using(var gzip = new GZipStream(output, CompressionLevel.Optimal))
		using(var writer = new TarWriter(gzip))
		{
			writer.WriteEntry(new PaxGlobalExtendedAttributesTarEntry(new Dictionary<string, string> { ["PackageName"] = name, ["Architecture"] = architecture, ["Version"] = "1.0" }));
		}

		File.WriteAllText(path[..^7] + ".sh", "#!/bin/sh\nexit 0\n");
		return path;
	}
	private static CommandContext Context(params string[] arguments) => new(new CommandExecutor(), CommandLine.Parse(Utility.FormatCommand("containerize", arguments))[0], new ContainerizeCommand(), null);
}
