//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zongsoft.Tools.Packager.Migration.Properties {
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zongsoft.Tools.Packager.Migration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 {0}: bucket {1} created. 的本地化字符串。
        /// </summary>
        internal static string BucketCreated {
            get {
                return ResourceManager.GetString("BucketCreated", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 {0}: bucket {1} already exists; skipped. 的本地化字符串。
        /// </summary>
        internal static string BucketExists {
            get {
                return ResourceManager.GetString("BucketExists", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Usage: Migrator apply|status|check &lt;migration.json&gt; &lt;state-directory&gt; 的本地化字符串。
        /// </summary>
        internal static string CommandUsage {
            get {
                return ResourceManager.GetString("CommandUsage", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Unknown database migrator. 的本地化字符串。
        /// </summary>
        internal static string DatabaseMigratorUnknown {
            get {
                return ResourceManager.GetString("DatabaseMigratorUnknown", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Unknown database provider. 的本地化字符串。
        /// </summary>
        internal static string DatabaseProviderUnknown {
            get {
                return ResourceManager.GetString("DatabaseProviderUnknown", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Migration &apos;{0}&apos; failed ({1}). See migration status; check the provider/server logs for details. 的本地化字符串。
        /// </summary>
        internal static string MigrationFailed {
            get {
                return ResourceManager.GetString("MigrationFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Migration has not completed for this package. Run the packaged migrate.sh apply before starting the service. 的本地化字符串。
        /// </summary>
        internal static string MigrationNotCompleted {
            get {
                return ResourceManager.GetString("MigrationNotCompleted", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Migration has not run. 的本地化字符串。
        /// </summary>
        internal static string MigrationNotRun {
            get {
                return ResourceManager.GetString("MigrationNotRun", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Starting {0} 的本地化字符串。
        /// </summary>
        internal static string MigrationStarting {
            get {
                return ResourceManager.GetString("MigrationStarting", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Migration runner failed ({0}). Check package files, runtime dependencies and parameter configuration. 的本地化字符串。
        /// </summary>
        internal static string RunnerFailed {
            get {
                return ResourceManager.GetString("RunnerFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Migration script checksum mismatch: {0} 的本地化字符串。
        /// </summary>
        internal static string ScriptChecksumMismatch {
            get {
                return ResourceManager.GetString("ScriptChecksumMismatch", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 {0}: {1} 的本地化字符串。
        /// </summary>
        internal static string ScriptExecuting {
            get {
                return ResourceManager.GetString("ScriptExecuting", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Migration script escapes its package directory. 的本地化字符串。
        /// </summary>
        internal static string ScriptPathInvalid {
            get {
                return ResourceManager.GetString("ScriptPathInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 TDengine WebSocket &apos;{0}&apos; failed (code {1}). 的本地化字符串。
        /// </summary>
        internal static string TDengineRequestFailed {
            get {
                return ResourceManager.GetString("TDengineRequestFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Invalid TDengine WebSocket response. 的本地化字符串。
        /// </summary>
        internal static string TDengineResponseInvalid {
            get {
                return ResourceManager.GetString("TDengineResponseInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 TDengine WebSocket response exceeds the size limit. 的本地化字符串。
        /// </summary>
        internal static string TDengineResponseTooLarge {
            get {
                return ResourceManager.GetString("TDengineResponseTooLarge", resourceCulture);
            }
        }
    }
}
