<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<OutputType>Exe</OutputType>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<IsPackable>false</IsPackable>
		<UseAppHost>true</UseAppHost>
		<PublishAot>true</PublishAot>
		<IsAotCompatible>true</IsAotCompatible>
		<AssemblyName>Zongsoft.Tools.Packager.Migrator</AssemblyName>
		<RollForward>Major</RollForward>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.2" />
		<PackageReference Include="MySqlConnector" Version="2.4.0" />
		<PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.10" />
		<PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.3" />
		<PackageReference Include="DuckDB.NET.Data.Full" Version="1.5.5" />
		<PackageReference Include="Npgsql" Version="8.0.9" />
		<PackageReference Include="AWSSDK.S3" Version="4.0.25.2" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Properties\Resources.Designer.cs">
			<AutoGen>True</AutoGen>
			<DesignTime>True</DesignTime>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
		<EmbeddedResource Update="Properties\Resources*.resx">
			<ManifestResourceName>Zongsoft.Tools.Packager.Migration.Properties.%(Filename)</ManifestResourceName>
		</EmbeddedResource>
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
			<CustomToolNamespace>Zongsoft.Tools.Packager.Migration.Properties</CustomToolNamespace>
		</EmbeddedResource>
	</ItemGroup>
	<Import Project="..\..\.shared\Migration.props" />
</Project>
