//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zongsoft.Tools.Migrator.Migration {
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MigrationResources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MigrationResources() {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zongsoft.Tools.Migrator.Migration.MigrationResources", typeof(MigrationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 Database must be an absolute path for the target operating system. 的本地化字符串。
        /// </summary>
        internal static string DatabasePathInvalid_Message {
            get {
                return ResourceManager.GetString("DatabasePathInvalid.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Invalid database Port. 的本地化字符串。
        /// </summary>
        internal static string DatabasePortInvalid_Message {
            get {
                return ResourceManager.GetString("DatabasePortInvalid.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Unknown migrator &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string MigratorUnknown_Message {
            get {
                return ResourceManager.GetString("MigratorUnknown.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Invalid migration parameter &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ParameterInvalid_Message {
            get {
                return ResourceManager.GetString("ParameterInvalid.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Missing parameter &apos;{0}&apos; for &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ParameterMissing_Message {
            get {
                return ResourceManager.GetString("ParameterMissing.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Migration parameter &apos;{0}&apos; exceeds one day. 的本地化字符串。
        /// </summary>
        internal static string ParameterTimeoutExceeded_Message {
            get {
                return ResourceManager.GetString("ParameterTimeoutExceeded.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Unknown parameter &apos;{0}&apos; for &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ParameterUnknown_Message {
            get {
                return ResourceManager.GetString("ParameterUnknown.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Invalid parameter &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ParameterValueInvalid_Message {
            get {
                return ResourceManager.GetString("ParameterValueInvalid.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Empty migration plan. 的本地化字符串。
        /// </summary>
        internal static string PlanEmpty_Message {
            get {
                return ResourceManager.GetString("PlanEmpty.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Invalid migration plan. 的本地化字符串。
        /// </summary>
        internal static string PlanInvalid_Message {
            get {
                return ResourceManager.GetString("PlanInvalid.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Migration target {0} does not match the current runtime {1}. 的本地化字符串。
        /// </summary>
        internal static string RuntimeMismatch_Message {
            get {
                return ResourceManager.GetString("RuntimeMismatch.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Unsupported migration runtime: {0}. 的本地化字符串。
        /// </summary>
        internal static string RuntimeUnsupported_Message {
            get {
                return ResourceManager.GetString("RuntimeUnsupported.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Invalid S3 Server URI. 的本地化字符串。
        /// </summary>
        internal static string S3ServerInvalid_Message {
            get {
                return ResourceManager.GetString("S3ServerInvalid.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 TrustServerCertificate is only supported by mssql. 的本地化字符串。
        /// </summary>
        internal static string TrustServerCertificateUnsupported_Message {
            get {
                return ResourceManager.GetString("TrustServerCertificateUnsupported.Message", resourceCulture);
            }
        }
    }
}
