//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zongsoft.Tools.Packager.Properties {
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zongsoft.Tools.Packager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 The command line is empty. 的本地化字符串。
        /// </summary>
        internal static string CommandLineEmpty_Message {
            get {
                return ResourceManager.GetString("CommandLineEmpty.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The &apos;{0}&apos; directory does not exist. 的本地化字符串。
        /// </summary>
        internal static string DirectoryNotExist_Message {
            get {
                return ResourceManager.GetString("DirectoryNotExist.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The &apos;{0}&apos; file does not exist. 的本地化字符串。
        /// </summary>
        internal static string FileNotExist_Message {
            get {
                return ResourceManager.GetString("FileNotExist.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Generated package entry conflicts with &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string GeneratedEntryConflicted {
            get {
                return ResourceManager.GetString("GeneratedEntryConflicted", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The daemon host location failed. 的本地化字符串。
        /// </summary>
        internal static string HostLocateFailed_Message {
            get {
                return ResourceManager.GetString("HostLocateFailed.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The version number is invalid. 的本地化字符串。
        /// </summary>
        internal static string InvalidVersion_Message {
            get {
                return ResourceManager.GetString("InvalidVersion.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Duplicate migrator aliases in parameter file: {0} 的本地化字符串。
        /// </summary>
        internal static string MigrationAliasesDuplicate {
            get {
                return ResourceManager.GetString("MigrationAliasesDuplicate", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Duplicate bucket name. 的本地化字符串。
        /// </summary>
        internal static string MigrationBucketDuplicate {
            get {
                return ResourceManager.GetString("MigrationBucketDuplicate", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Invalid bucket name &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string MigrationBucketNameInvalid {
            get {
                return ResourceManager.GetString("MigrationBucketNameInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Bucket &apos;{0}&apos; has invalid or duplicate options. Use public/private, encryption:sse-s3/sse-kms with optional encryption.key for KMS, versioning:enabled/suspended, and tag.&lt;name&gt;:&lt;value&gt; (up to 50 tags; key/value limits: 128/256 characters; aws: keys are reserved). 的本地化字符串。
        /// </summary>
        internal static string MigrationBucketOptionsInvalid {
            get {
                return ResourceManager.GetString("MigrationBucketOptionsInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Database entries must be SQL paths without values. 的本地化字符串。
        /// </summary>
        internal static string MigrationDatabaseEntryInvalid {
            get {
                return ResourceManager.GetString("MigrationDatabaseEntryInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 {0}:{1} [{2}]: {3} 的本地化字符串。
        /// </summary>
        internal static string MigrationEntryError {
            get {
                return ResourceManager.GetString("MigrationEntryError", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Migration file must use .ini: {0} 的本地化字符串。
        /// </summary>
        internal static string MigrationFileExtension {
            get {
                return ResourceManager.GetString("MigrationFileExtension", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Warning: No migration INI files found for {0}; skipped. 的本地化字符串。
        /// </summary>
        internal static string MigrationFilesMissing {
            get {
                return ResourceManager.GetString("MigrationFilesMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Migration packages require net8.0, net9.0 or net10.0. 的本地化字符串。
        /// </summary>
        internal static string MigrationFrameworkInvalid {
            get {
                return ResourceManager.GetString("MigrationFrameworkInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A migration package requires a locatable service host or --daemon:none. 的本地化字符串。
        /// </summary>
        internal static string MigrationHostRequired {
            get {
                return ResourceManager.GetString("MigrationHostRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Invalid package identity for migration state. 的本地化字符串。
        /// </summary>
        internal static string MigrationIdentityInvalid {
            get {
                return ResourceManager.GetString("MigrationIdentityInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Migration packages use a fixed installation path; rebuild with --install-path. 的本地化字符串。
        /// </summary>
        internal static string MigrationInstallPathFixed {
            get {
                return ResourceManager.GetString("MigrationInstallPathFixed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Migration installation paths must be absolute Linux paths containing letters, digits, &apos;.&apos;, &apos;_&apos;, &apos;+&apos;, &apos;-&apos; and directory separators. 的本地化字符串。
        /// </summary>
        internal static string MigrationInstallPathInvalid {
            get {
                return ResourceManager.GetString("MigrationInstallPathInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Migration has not completed for this package. 的本地化字符串。
        /// </summary>
        internal static string MigrationNotCompleted {
            get {
                return ResourceManager.GetString("MigrationNotCompleted", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 {0} [{1}]: {2} 的本地化字符串。
        /// </summary>
        internal static string MigrationParameterError {
            get {
                return ResourceManager.GetString("MigrationParameterError", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 No migration parameters found for &apos;{0}&apos; ({1}). Searched: {2} 的本地化字符串。
        /// </summary>
        internal static string MigrationParametersMissing {
            get {
                return ResourceManager.GetString("MigrationParametersMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Invalid or unresolved parameter &apos;{0}&apos; at {1}:{2}. 的本地化字符串。
        /// </summary>
        internal static string MigrationParameterUnresolved {
            get {
                return ResourceManager.GetString("MigrationParameterUnresolved", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Package entry uses a reserved migration path: {0} 的本地化字符串。
        /// </summary>
        internal static string MigrationPathReserved {
            get {
                return ResourceManager.GetString("MigrationPathReserved", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 --migration requires at least one INI path. 的本地化字符串。
        /// </summary>
        internal static string MigrationPathsRequired {
            get {
                return ResourceManager.GetString("MigrationPathsRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Migration packages support linux-x64 and linux-arm64. 的本地化字符串。
        /// </summary>
        internal static string MigrationPlatformInvalid {
            get {
                return ResourceManager.GetString("MigrationPlatformInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Invalid or duplicate INI entry/section in &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string MigrationProfileInvalid {
            get {
                return ResourceManager.GetString("MigrationProfileInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Duplicate section &apos;{0}&apos; at {1}:{2}. 的本地化字符串。
        /// </summary>
        internal static string MigrationProfileSectionDuplicate {
            get {
                return ResourceManager.GetString("MigrationProfileSectionDuplicate", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Unknown migration provider. 的本地化字符串。
        /// </summary>
        internal static string MigrationProviderUnknown {
            get {
                return ResourceManager.GetString("MigrationProviderUnknown", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The native migrator {0} is not a valid {1} ELF executable. 的本地化字符串。
        /// </summary>
        internal static string MigrationRuntimeInvalid {
            get {
                return ResourceManager.GetString("MigrationRuntimeInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The packaged migration runtime is missing. Rebuild/reinstall dotnet-pack. 的本地化字符串。
        /// </summary>
        internal static string MigrationRuntimeMissing {
            get {
                return ResourceManager.GetString("MigrationRuntimeMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Migration script pattern has no matches: {0} 的本地化字符串。
        /// </summary>
        internal static string MigrationScriptsMissing {
            get {
                return ResourceManager.GetString("MigrationScriptsMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Duplicate migrator section. 的本地化字符串。
        /// </summary>
        internal static string MigrationSectionDuplicate {
            get {
                return ResourceManager.GetString("MigrationSectionDuplicate", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Invalid migration section at {0}:{1}. 的本地化字符串。
        /// </summary>
        internal static string MigrationSectionInvalid {
            get {
                return ResourceManager.GetString("MigrationSectionInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Migration entries require a section: {0} 的本地化字符串。
        /// </summary>
        internal static string MigrationSectionRequired {
            get {
                return ResourceManager.GetString("MigrationSectionRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Database scripts must use .sql. 的本地化字符串。
        /// </summary>
        internal static string MigrationSqlExtension {
            get {
                return ResourceManager.GetString("MigrationSqlExtension", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 No migration tasks were specified. 的本地化字符串。
        /// </summary>
        internal static string MigrationTasksMissing {
            get {
                return ResourceManager.GetString("MigrationTasksMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The migration variable &apos;{0}&apos; is undefined. 的本地化字符串。
        /// </summary>
        internal static string MigrationVariableUndefined_Message {
            get {
                return ResourceManager.GetString("MigrationVariableUndefined.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Migration wildcards are supported only in the file name. 的本地化字符串。
        /// </summary>
        internal static string MigrationWildcardInvalid {
            get {
                return ResourceManager.GetString("MigrationWildcardInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Invalid MySQL DELIMITER. 的本地化字符串。
        /// </summary>
        internal static string MySqlDelimiterInvalid {
            get {
                return ResourceManager.GetString("MySqlDelimiterInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The source file &apos;{0}&apos; conflicts with an existing package entry &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string PackageEntryConflicted_Message {
            get {
                return ResourceManager.GetString("PackageEntryConflicted.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The &apos;{0}&apos; package file generated successfully. 的本地化字符串。
        /// </summary>
        internal static string PackageGeneratedSuccessfully_Message {
            get {
                return ResourceManager.GetString("PackageGeneratedSuccessfully.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The source path &apos;{0}&apos; does not exist. 的本地化字符串。
        /// </summary>
        internal static string PathNotExist_Message {
            get {
                return ResourceManager.GetString("PathNotExist.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Repeated GO batches are not supported. 的本地化字符串。
        /// </summary>
        internal static string SqlServerGoRepeatUnsupported {
            get {
                return ResourceManager.GetString("SqlServerGoRepeatUnsupported", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The &apos;{0}&apos; variable in the &apos;{1}&apos; expression is undefined. 的本地化字符串。
        /// </summary>
        internal static string VariableUndefined_Message {
            get {
                return ResourceManager.GetString("VariableUndefined.Message", resourceCulture);
            }
        }
    }
}
