//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zongsoft.Tools.Packager.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zongsoft.Tools.Packager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The command line is empty..
        /// </summary>
        internal static string CommandLineEmpty_Message {
            get {
                return ResourceManager.GetString("CommandLineEmpty.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid Debian relationship in field &quot;{0}&quot;..
        /// </summary>
        internal static string DebianRelationshipInvalid_Message {
            get {
                return ResourceManager.GetString("DebianRelationshipInvalid.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; directory does not exist..
        /// </summary>
        internal static string DirectoryNotExist_Message {
            get {
                return ResourceManager.GetString("DirectoryNotExist.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; file does not exist..
        /// </summary>
        internal static string FileNotExist_Message {
            get {
                return ResourceManager.GetString("FileNotExist.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Generated package entry conflicts with &apos;{0}&apos;..
        /// </summary>
        internal static string GeneratedEntryConflicted_Message {
            get {
                return ResourceManager.GetString("GeneratedEntryConflicted.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The daemon host location failed..
        /// </summary>
        internal static string HostLocateFailed_Message {
            get {
                return ResourceManager.GetString("HostLocateFailed.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The version number is invalid..
        /// </summary>
        internal static string InvalidVersion_Message {
            get {
                return ResourceManager.GetString("InvalidVersion.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A migration package requires a locatable service host or --daemon:none..
        /// </summary>
        internal static string MigrationHostRequired_Message {
            get {
                return ResourceManager.GetString("MigrationHostRequired.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid package identity for migration state..
        /// </summary>
        internal static string MigrationIdentityInvalid_Message {
            get {
                return ResourceManager.GetString("MigrationIdentityInvalid.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Migration packages use a fixed installation path; rebuild with --install-path..
        /// </summary>
        internal static string MigrationInstallPathFixed {
            get {
                return ResourceManager.GetString("MigrationInstallPathFixed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Migration installation paths must be absolute Linux paths containing letters, digits, &apos;.&apos;, &apos;_&apos;, &apos;+&apos;, &apos;-&apos; and directory separators..
        /// </summary>
        internal static string MigrationInstallPathInvalid_Message {
            get {
                return ResourceManager.GetString("MigrationInstallPathInvalid.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Package entry uses a reserved migration path: {0}.
        /// </summary>
        internal static string MigrationPathReserved_Message {
            get {
                return ResourceManager.GetString("MigrationPathReserved.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Migration supports Linux x64/arm64 and Windows x64..
        /// </summary>
        internal static string MigrationPlatformInvalid_Message {
            get {
                return ResourceManager.GetString("MigrationPlatformInvalid.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The required migrator artifact was not found: {0}.
        /// </summary>
        internal static string MigratorArtifactMissing_Message {
            get {
                return ResourceManager.GetString("MigratorArtifactMissing.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The migrator artifacts &quot;{0}&quot; and &quot;{1}&quot; were not found.{3}Searched directories:{2}.
        /// </summary>
        internal static string MigratorArtifactsNotFound_Message {
            get {
                return ResourceManager.GetString("MigratorArtifactsNotFound.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The migrator archive {0} must contain Migrator metadata and target runtime {1}..
        /// </summary>
        internal static string MigratorMetadataInvalid_Message {
            get {
                return ResourceManager.GetString("MigratorMetadataInvalid.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Specify a migrator input name, optionally including its directory, without edition, version, runtime or file extension..
        /// </summary>
        internal static string MigratorNameInvalid_Message {
            get {
                return ResourceManager.GetString("MigratorNameInvalid.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid MySQL DELIMITER..
        /// </summary>
        internal static string MySqlDelimiterInvalid_Message {
            get {
                return ResourceManager.GetString("MySqlDelimiterInvalid.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The variable normalizer has not been initialized..
        /// </summary>
        internal static string NormalizerNotInitialized_Message {
            get {
                return ResourceManager.GetString("NormalizerNotInitialized.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The source file &apos;{0}&apos; conflicts with an existing package entry &apos;{1}&apos;..
        /// </summary>
        internal static string PackageEntryConflicted_Message {
            get {
                return ResourceManager.GetString("PackageEntryConflicted.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File and directory entries conflict at &quot;{0}&quot;..
        /// </summary>
        internal static string PackageEntryTypeConflict_Message {
            get {
                return ResourceManager.GetString("PackageEntryTypeConflict.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; package file generated successfully..
        /// </summary>
        internal static string PackageGeneratedSuccessfully_Message {
            get {
                return ResourceManager.GetString("PackageGeneratedSuccessfully.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid package entry path &quot;{0}&quot;..
        /// </summary>
        internal static string PackagePathInvalid_Message {
            get {
                return ResourceManager.GetString("PackagePathInvalid.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The source path &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string PathNotExist_Message {
            get {
                return ResourceManager.GetString("PathNotExist.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot resolve variable &quot;{0}&quot; in the source directory before application identity is determined. Specify the identity option or use a source path without it..
        /// </summary>
        internal static string SourceVariableUndefined_Message {
            get {
                return ResourceManager.GetString("SourceVariableUndefined.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The --edition &quot;{1}&quot; does not exist in &quot;{0}&quot;..
        /// </summary>
        internal static string SourceVersionEditionMissing_Message {
            get {
                return ResourceManager.GetString("SourceVersionEditionMissing.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The source version file &quot;{0}&quot; contains multiple editions. Specify --edition..
        /// </summary>
        internal static string SourceVersionEditionRequired_Message {
            get {
                return ResourceManager.GetString("SourceVersionEditionRequired.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid --name or --edition for source version file &quot;{0}&quot;..
        /// </summary>
        internal static string SourceVersionIdentityInvalid_Message {
            get {
                return ResourceManager.GetString("SourceVersionIdentityInvalid.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A valid nonzero --version or selected source version is required. Source: {0}.
        /// </summary>
        internal static string SourceVersionInvalid_Message {
            get {
                return ResourceManager.GetString("SourceVersionInvalid.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot load the source version file &quot;{0}&quot;..
        /// </summary>
        internal static string SourceVersionLoadFailed_Message {
            get {
                return ResourceManager.GetString("SourceVersionLoadFailed.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The --name &quot;{1}&quot; does not match application &quot;{2}&quot; in &quot;{0}&quot;..
        /// </summary>
        internal static string SourceVersionNameMismatch_Message {
            get {
                return ResourceManager.GetString("SourceVersionNameMismatch.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A nonempty --name is required when no source version is available. Source: {0}.
        /// </summary>
        internal static string SourceVersionNameRequired_Message {
            get {
                return ResourceManager.GetString("SourceVersionNameRequired.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Package &quot;{0}&quot; was generated, but updating source version file &quot;{1}&quot; failed..
        /// </summary>
        internal static string SourceVersionSaveFailed_Message {
            get {
                return ResourceManager.GetString("SourceVersionSaveFailed.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Repeated GO batches are not supported..
        /// </summary>
        internal static string SqlServerGoRepeatUnsupported_Message {
            get {
                return ResourceManager.GetString("SqlServerGoRepeatUnsupported.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This option requires a file path and does not accept inline text..
        /// </summary>
        internal static string TextSourceFileRequired_Message {
            get {
                return ResourceManager.GetString("TextSourceFileRequired.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The text source file &quot;{0}&quot; does not exist..
        /// </summary>
        internal static string TextSourceMissing_Message {
            get {
                return ResourceManager.GetString("TextSourceMissing.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Variable &quot;{0}&quot; is undefined or contains a cyclic reference..
        /// </summary>
        internal static string VariableResolutionFailed_Message {
            get {
                return ResourceManager.GetString("VariableResolutionFailed.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; variable in the &apos;{1}&apos; expression is undefined..
        /// </summary>
        internal static string VariableUndefined_Message {
            get {
                return ResourceManager.GetString("VariableUndefined.Message", resourceCulture);
            }
        }
    }
}
