//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zongsoft.Tools.Migrator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zongsoft.Tools.Migrator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify --name, --version, --platform and at least one migration input path..
        /// </summary>
        internal static string CommandLineEmpty_Message {
            get {
                return ResourceManager.GetString("CommandLineEmpty.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a standalone native migration archive and launcher..
        /// </summary>
        internal static string MigrateCommand_Description {
            get {
                return ResourceManager.GetString("MigrateCommand.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration archive: {0}
        ///Launcher: {1}.
        /// </summary>
        internal static string MigrateGenerated {
            get {
                return ResourceManager.GetString("MigrateGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No migration input files were found; no output was generated..
        /// </summary>
        internal static string MigrateInputsMissing_Message {
            get {
                return ResourceManager.GetString("MigrateInputsMissing.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A native migrator for macOS is not available..
        /// </summary>
        internal static string MigrateMacUnavailable_Message {
            get {
                return ResourceManager.GetString("MigrateMacUnavailable.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration output already exists or is a directory: {0}. Use --overwrite to replace files..
        /// </summary>
        internal static string MigrateOutputExists_Message {
            get {
                return ResourceManager.GetString("MigrateOutputExists.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a specific operating system instead of unix..
        /// </summary>
        internal static string MigrateUnixAmbiguous_Message {
            get {
                return ResourceManager.GetString("MigrateUnixAmbiguous.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version file &quot;{0}&quot; does not contain Edition &quot;{1}&quot;..
        /// </summary>
        internal static string MigrateVersionEditionMissing_Message {
            get {
                return ResourceManager.GetString("MigrateVersionEditionMissing.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version file &quot;{0}&quot; contains multiple Editions. Specify --edition..
        /// </summary>
        internal static string MigrateVersionEditionRequired_Message {
            get {
                return ResourceManager.GetString("MigrateVersionEditionRequired.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected version in &quot;{0}&quot; must be nonzero..
        /// </summary>
        internal static string MigrateVersionFileInvalid_Message {
            get {
                return ResourceManager.GetString("MigrateVersionFileInvalid.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a valid nonzero version..
        /// </summary>
        internal static string MigrateVersionInvalid_Message {
            get {
                return ResourceManager.GetString("MigrateVersionInvalid.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read the version file &quot;{0}&quot;, or its contents are invalid..
        /// </summary>
        internal static string MigrateVersionLoadFailed_Message {
            get {
                return ResourceManager.GetString("MigrateVersionLoadFailed.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate migrator aliases in parameter file: {0}.
        /// </summary>
        internal static string MigrationAliasesDuplicate_Message {
            get {
                return ResourceManager.GetString("MigrationAliasesDuplicate.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate bucket name..
        /// </summary>
        internal static string MigrationBucketDuplicate_Message {
            get {
                return ResourceManager.GetString("MigrationBucketDuplicate.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid bucket name &apos;{0}&apos;..
        /// </summary>
        internal static string MigrationBucketNameInvalid_Message {
            get {
                return ResourceManager.GetString("MigrationBucketNameInvalid.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bucket &apos;{0}&apos; has invalid or duplicate options. Use public/private, encryption:sse-s3/sse-kms with optional encryption.key for KMS, versioning:enabled/suspended, and tag.&lt;name&gt;:&lt;value&gt; (up to 50 tags; key/value limits: 128/256 characters; aws: keys are reserved)..
        /// </summary>
        internal static string MigrationBucketOptionsInvalid_Message {
            get {
                return ResourceManager.GetString("MigrationBucketOptionsInvalid.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database entries must be SQL paths without values..
        /// </summary>
        internal static string MigrationDatabaseEntryInvalid_Message {
            get {
                return ResourceManager.GetString("MigrationDatabaseEntryInvalid.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:{1} [{2}]:{3}.
        /// </summary>
        internal static string MigrationEntryError_Message {
            get {
                return ResourceManager.GetString("MigrationEntryError.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration files must use the .migration extension (INI content): {0}.
        /// </summary>
        internal static string MigrationFileExtension_Message {
            get {
                return ResourceManager.GetString("MigrationFileExtension.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: no migration file matches {0}; skipped..
        /// </summary>
        internal static string MigrationFilesMissing {
            get {
                return ResourceManager.GetString("MigrationFilesMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid package identity for migration state..
        /// </summary>
        internal static string MigrationIdentityInvalid_Message {
            get {
                return ResourceManager.GetString("MigrationIdentityInvalid.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration has not completed for this package..
        /// </summary>
        internal static string MigrationNotCompleted {
            get {
                return ResourceManager.GetString("MigrationNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [{1}]:{2}.
        /// </summary>
        internal static string MigrationParameterError_Message {
            get {
                return ResourceManager.GetString("MigrationParameterError.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No migration parameters found for &apos;{0}&apos;. Searched:{1}.
        /// </summary>
        internal static string MigrationParametersMissing_Message {
            get {
                return ResourceManager.GetString("MigrationParametersMissing.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or unresolved parameter &apos;{0}&apos; at {1}:{2}..
        /// </summary>
        internal static string MigrationParameterUnresolved_Message {
            get {
                return ResourceManager.GetString("MigrationParameterUnresolved.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify at least one .migration file path..
        /// </summary>
        internal static string MigrationPathsRequired_Message {
            get {
                return ResourceManager.GetString("MigrationPathsRequired.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration supports Linux x64/arm64 and Windows x64..
        /// </summary>
        internal static string MigrationPlatformInvalid_Message {
            get {
                return ResourceManager.GetString("MigrationPlatformInvalid.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or duplicate INI entry/section in &apos;{0}&apos;..
        /// </summary>
        internal static string MigrationProfileInvalid_Message {
            get {
                return ResourceManager.GetString("MigrationProfileInvalid.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate section &apos;{0}&apos; at {1}:{2}..
        /// </summary>
        internal static string MigrationProfileSectionDuplicate_Message {
            get {
                return ResourceManager.GetString("MigrationProfileSectionDuplicate.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown migration provider..
        /// </summary>
        internal static string MigrationProviderUnknown_Message {
            get {
                return ResourceManager.GetString("MigrationProviderUnknown.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The native migrator {0} is not a valid {1} executable..
        /// </summary>
        internal static string MigrationRuntimeInvalid_Message {
            get {
                return ResourceManager.GetString("MigrationRuntimeInvalid.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The packaged migration runtime is missing. Rebuild/reinstall dotnet-pack..
        /// </summary>
        internal static string MigrationRuntimeMissing_Message {
            get {
                return ResourceManager.GetString("MigrationRuntimeMissing.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration script pattern has no matches: {0}.
        /// </summary>
        internal static string MigrationScriptsMissing_Message {
            get {
                return ResourceManager.GetString("MigrationScriptsMissing.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate migrator section..
        /// </summary>
        internal static string MigrationSectionDuplicate_Message {
            get {
                return ResourceManager.GetString("MigrationSectionDuplicate.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid migration section at {0}:{1}..
        /// </summary>
        internal static string MigrationSectionInvalid_Message {
            get {
                return ResourceManager.GetString("MigrationSectionInvalid.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration entries require a section: {0}.
        /// </summary>
        internal static string MigrationSectionRequired_Message {
            get {
                return ResourceManager.GetString("MigrationSectionRequired.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database scripts must use .sql..
        /// </summary>
        internal static string MigrationSqlExtension_Message {
            get {
                return ResourceManager.GetString("MigrationSqlExtension.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No migration tasks were specified..
        /// </summary>
        internal static string MigrationTasksMissing_Message {
            get {
                return ResourceManager.GetString("MigrationTasksMissing.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The migration variable &apos;{0}&apos; is undefined..
        /// </summary>
        internal static string MigrationVariableUndefined_Message {
            get {
                return ResourceManager.GetString("MigrationVariableUndefined.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid MySQL DELIMITER..
        /// </summary>
        internal static string MySqlDelimiterInvalid_Message {
            get {
                return ResourceManager.GetString("MySqlDelimiterInvalid.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable normalizer has not been initialized..
        /// </summary>
        internal static string NormalizerNotInitialized_Message {
            get {
                return ResourceManager.GetString("NormalizerNotInitialized.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeated GO batches are not supported..
        /// </summary>
        internal static string SqlServerGoRepeatUnsupported_Message {
            get {
                return ResourceManager.GetString("SqlServerGoRepeatUnsupported.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option requires a file path and does not accept inline text..
        /// </summary>
        internal static string TextSourceFileRequired_Message {
            get {
                return ResourceManager.GetString("TextSourceFileRequired.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text source file &quot;{0}&quot; does not exist..
        /// </summary>
        internal static string TextSourceMissing_Message {
            get {
                return ResourceManager.GetString("TextSourceMissing.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable &quot;{0}&quot; is undefined or contains a cyclic reference..
        /// </summary>
        internal static string VariableResolutionFailed_Message {
            get {
                return ResourceManager.GetString("VariableResolutionFailed.Message", resourceCulture);
            }
        }
    }
}
