<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
		<Version>0.12.0</Version>
		<PackAsTool>true</PackAsTool>
		<ToolCommandName>dotnet-pack</ToolCommandName>
		<PackageDescription>The Zongsoft Packaging .NET Tool.</PackageDescription>
		<Product>Zongsoft Packaging Tool</Product>
		<Description>Zongsoft Application Packaging Tool.</Description>
		<PackageProjectUrl>https://github.com/Zongsoft/tools/tree/main/packager</PackageProjectUrl>
		<RepositoryUrl>https://github.com/Zongsoft/tools/tree/main/packager</RepositoryUrl>
		<ApplicationIcon>..\..\zongsoft-logo.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="..\..\.shared\VariableExpander.cs" Link="Shared\VariableExpander.cs" />
		<InternalsVisibleTo Include="Zongsoft.Tools.Packager.Tests" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\docs\**\*" Pack="true" PackagePath="docs/%(RecursiveDir)" />
		<None Include="..\README.md" Pack="true" PackagePath="\" />
		<None Include="..\README.zh-Hans.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<Choose>
		<When Condition="$(Configuration)=='Debug'">
			<ItemGroup>
				<Reference Include="Zongsoft.Core">
					<HintPath>..\..\..\framework\Zongsoft.Core\src\bin\$(Configuration)\$(TargetFramework)\Zongsoft.Core.dll</HintPath>
				</Reference>
			</ItemGroup>
		</When>
		<Otherwise>
			<ItemGroup>
				<PackageReference Include="Zongsoft.Core" />
			</ItemGroup>
		</Otherwise>
	</Choose>

	<ItemGroup>
		<Compile Update="Properties\Resources.Designer.cs">
			<AutoGen>True</AutoGen>
			<DesignTime>True</DesignTime>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>
</Project>
