//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zongsoft.Tools.Containerizer.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zongsoft.Tools.Containerizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The installation package requires a matching distribution family. 的本地化字符串。
        /// </summary>
        internal static string ApplicationBuilder_1_Message {
            get {
                return ResourceManager.GetString("ApplicationBuilder.1.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The explicit runtime constraint conflicts with runtimeconfig.json. 的本地化字符串。
        /// </summary>
        internal static string ApplicationBuilder_10_Message {
            get {
                return ResourceManager.GetString("ApplicationBuilder.10.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A precise supported runtime version is required. 的本地化字符串。
        /// </summary>
        internal static string ApplicationBuilder_11_Message {
            get {
                return ResourceManager.GetString("ApplicationBuilder.11.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The package must supply one unambiguous service entry and working directory. 的本地化字符串。
        /// </summary>
        internal static string ApplicationBuilder_3_Message {
            get {
                return ResourceManager.GetString("ApplicationBuilder.3.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The package has unsupported or ambiguous systemd startup arguments. 的本地化字符串。
        /// </summary>
        internal static string ApplicationBuilder_4_Message {
            get {
                return ResourceManager.GetString("ApplicationBuilder.4.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The package must supply a foreground executable service entry. 的本地化字符串。
        /// </summary>
        internal static string ApplicationBuilder_5_Message {
            get {
                return ResourceManager.GetString("ApplicationBuilder.5.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The package has an unsupported systemd environment declaration. 的本地化字符串。
        /// </summary>
        internal static string ApplicationBuilder_6_Message {
            get {
                return ResourceManager.GetString("ApplicationBuilder.6.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The package listener cannot be converted into a container binding. 的本地化字符串。
        /// </summary>
        internal static string ApplicationBuilder_7_Message {
            get {
                return ResourceManager.GetString("ApplicationBuilder.7.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The application healthcheck could not be inferred from package metadata. 的本地化字符串。
        /// </summary>
        internal static string ApplicationBuilder_8_Message {
            get {
                return ResourceManager.GetString("ApplicationBuilder.8.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The entry runtimeconfig.json is missing or ambiguous. 的本地化字符串。
        /// </summary>
        internal static string ApplicationBuilder_9_Message {
            get {
                return ResourceManager.GetString("ApplicationBuilder.9.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: invalid application listener or HTTP health configuration ({1}). 的本地化字符串。
        /// </summary>
        internal static string ApplicationHealth_Invalid_Message {
            get {
                return ResourceManager.GetString("ApplicationHealth.Invalid.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A command is required. 的本地化字符串。
        /// </summary>
        internal static string Arguments_1_Message {
            get {
                return ResourceManager.GetString("Arguments.1.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 list does not accept --name. 的本地化字符串。
        /// </summary>
        internal static string Arguments_10_Message {
            get {
                return ResourceManager.GetString("Arguments.10.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 --name is required. 的本地化字符串。
        /// </summary>
        internal static string Arguments_11_Message {
            get {
                return ResourceManager.GetString("Arguments.11.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown command. 的本地化字符串。
        /// </summary>
        internal static string Arguments_2_Message {
            get {
                return ResourceManager.GetString("Arguments.2.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An option was specified more than once. 的本地化字符串。
        /// </summary>
        internal static string Arguments_3_Message {
            get {
                return ResourceManager.GetString("Arguments.3.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 --tail requires a nonnegative number. 的本地化字符串。
        /// </summary>
        internal static string Arguments_4_Message {
            get {
                return ResourceManager.GetString("Arguments.4.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown option or option not valid for this command. 的本地化字符串。
        /// </summary>
        internal static string Arguments_5_Message {
            get {
                return ResourceManager.GetString("Arguments.5.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An option value is missing. 的本地化字符串。
        /// </summary>
        internal static string Arguments_6_Message {
            get {
                return ResourceManager.GetString("Arguments.6.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exactly one node bundle path is required. 的本地化字符串。
        /// </summary>
        internal static string Arguments_7_Message {
            get {
                return ResourceManager.GetString("Arguments.7.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At most one component is allowed. 的本地化字符串。
        /// </summary>
        internal static string Arguments_8_Message {
            get {
                return ResourceManager.GetString("Arguments.8.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This command has no positional arguments. 的本地化字符串。
        /// </summary>
        internal static string Arguments_9_Message {
            get {
                return ResourceManager.GetString("Arguments.9.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No base image profile is available. 的本地化字符串。
        /// </summary>
        internal static string BootstrapBuilder_1_Message {
            get {
                return ResourceManager.GetString("BootstrapBuilder.1.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RHEL bootstrap requires an entitled BaseOS/AppStream resolver profile; UBI/Rocky packages are not substitutes. Configure and validate the RHEL repository profile before building. 的本地化字符串。
        /// </summary>
        internal static string BootstrapBuilder_2_Message {
            get {
                return ResourceManager.GetString("BootstrapBuilder.2.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bootstrap package metadata is incomplete. 的本地化字符串。
        /// </summary>
        internal static string BootstrapBuilder_3_Message {
            get {
                return ResourceManager.GetString("BootstrapBuilder.3.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The bootstrap dependency closure is incomplete. 的本地化字符串。
        /// </summary>
        internal static string BootstrapBuilder_4_Message {
            get {
                return ResourceManager.GetString("BootstrapBuilder.4.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bootstrap profile identity or dependency metadata is incomplete. 的本地化字符串。
        /// </summary>
        internal static string BootstrapBuilder_5_Message {
            get {
                return ResourceManager.GetString("BootstrapBuilder.5.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bootstrap package metadata is invalid. 的本地化字符串。
        /// </summary>
        internal static string BootstrapBuilder_6_Message {
            get {
                return ResourceManager.GetString("BootstrapBuilder.6.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bootstrap package content does not match its lock. 的本地化字符串。
        /// </summary>
        internal static string BootstrapBuilder_7_Message {
            get {
                return ResourceManager.GetString("BootstrapBuilder.7.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bootstrap package architecture does not match its profile. 的本地化字符串。
        /// </summary>
        internal static string BootstrapBuilder_8_Message {
            get {
                return ResourceManager.GetString("BootstrapBuilder.8.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning: could not remove build resource {0} with {1}. {2} 的本地化字符串。
        /// </summary>
        internal static string BuildResources_Cleanup_Message {
            get {
                return ResourceManager.GetString("BuildResources.Cleanup.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected a node bundle directory or .tar.gz archive. 的本地化字符串。
        /// </summary>
        internal static string Bundle_1_Message {
            get {
                return ResourceManager.GetString("Bundle.1.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid service identity or kind. 的本地化字符串。
        /// </summary>
        internal static string Bundle_10_Message {
            get {
                return ResourceManager.GetString("Bundle.10.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid locked image identity. 的本地化字符串。
        /// </summary>
        internal static string Bundle_11_Message {
            get {
                return ResourceManager.GetString("Bundle.11.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offline image archive is missing. 的本地化字符串。
        /// </summary>
        internal static string Bundle_12_Message {
            get {
                return ResourceManager.GetString("Bundle.12.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application images must be offline. 的本地化字符串。
        /// </summary>
        internal static string Bundle_13_Message {
            get {
                return ResourceManager.GetString("Bundle.13.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid locked migration list. 的本地化字符串。
        /// </summary>
        internal static string Bundle_14_Message {
            get {
                return ResourceManager.GetString("Bundle.14.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Migration identity mismatch. 的本地化字符串。
        /// </summary>
        internal static string Bundle_15_Message {
            get {
                return ResourceManager.GetString("Bundle.15.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid application or component identity. 的本地化字符串。
        /// </summary>
        internal static string Bundle_16_Message {
            get {
                return ResourceManager.GetString("Bundle.16.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsafe Linux path. 的本地化字符串。
        /// </summary>
        internal static string Bundle_17_Message {
            get {
                return ResourceManager.GetString("Bundle.17.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsupported node protocol schema. 的本地化字符串。
        /// </summary>
        internal static string Bundle_2_Message {
            get {
                return ResourceManager.GetString("Bundle.2.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid node identity or target. 的本地化字符串。
        /// </summary>
        internal static string Bundle_3_Message {
            get {
                return ResourceManager.GetString("Bundle.3.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid or duplicate file checksum record. 的本地化字符串。
        /// </summary>
        internal static string Bundle_4_Message {
            get {
                return ResourceManager.GetString("Bundle.4.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bundle integrity check failed: {0} 的本地化字符串。
        /// </summary>
        internal static string Bundle_5_Message {
            get {
                return ResourceManager.GetString("Bundle.5.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Required bundle asset is missing: {0} 的本地化字符串。
        /// </summary>
        internal static string Bundle_6_Message {
            get {
                return ResourceManager.GetString("Bundle.6.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid checksums.sha256. 的本地化字符串。
        /// </summary>
        internal static string Bundle_7_Message {
            get {
                return ResourceManager.GetString("Bundle.7.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checksum manifest differs from the node lock. 的本地化字符串。
        /// </summary>
        internal static string Bundle_8_Message {
            get {
                return ResourceManager.GetString("Bundle.8.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Untracked file in node bundle. 的本地化字符串。
        /// </summary>
        internal static string Bundle_9_Message {
            get {
                return ResourceManager.GetString("Bundle.9.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The installation executor requires Linux. 的本地化字符串。
        /// </summary>
        internal static string DockerHost_1_Message {
            get {
                return ResourceManager.GetString("DockerHost.1.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The exact bootstrap package is unavailable. 的本地化字符串。
        /// </summary>
        internal static string DockerHost_10_Message {
            get {
                return ResourceManager.GetString("DockerHost.10.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloaded bootstrap package failed integrity checks. 的本地化字符串。
        /// </summary>
        internal static string DockerHost_11_Message {
            get {
                return ResourceManager.GetString("DockerHost.11.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bootstrap package checksum mismatch. 的本地化字符串。
        /// </summary>
        internal static string DockerHost_12_Message {
            get {
                return ResourceManager.GetString("DockerHost.12.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bootstrap package transaction failed with exit code {0}; application state was retained. 的本地化字符串。
        /// </summary>
        internal static string DockerHost_13_Message {
            get {
                return ResourceManager.GetString("DockerHost.13.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Imported image identity/platform mismatch. 的本地化字符串。
        /// </summary>
        internal static string DockerHost_14_Message {
            get {
                return ResourceManager.GetString("DockerHost.14.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A persistent path overlaps another application&apos;s registered data. 的本地化字符串。
        /// </summary>
        internal static string DockerHost_15_Message {
            get {
                return ResourceManager.GetString("DockerHost.15.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A nonempty persistent directory has no matching ownership record. 的本地化字符串。
        /// </summary>
        internal static string DockerHost_16_Message {
            get {
                return ResourceManager.GetString("DockerHost.16.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Persistent directory ownership marker differs from the registry. 的本地化字符串。
        /// </summary>
        internal static string DockerHost_17_Message {
            get {
                return ResourceManager.GetString("DockerHost.17.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected exactly one container for a service. 的本地化字符串。
        /// </summary>
        internal static string DockerHost_18_Message {
            get {
                return ResourceManager.GetString("DockerHost.18.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service container is missing or ambiguous. 的本地化字符串。
        /// </summary>
        internal static string DockerHost_19_Message {
            get {
                return ResourceManager.GetString("DockerHost.19.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Installation commands require root. 的本地化字符串。
        /// </summary>
        internal static string DockerHost_2_Message {
            get {
                return ResourceManager.GetString("DockerHost.2.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service has no protocol/template healthcheck. 的本地化字符串。
        /// </summary>
        internal static string DockerHost_20_Message {
            get {
                return ResourceManager.GetString("DockerHost.20.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service failed its healthcheck; maintenance is retained. 的本地化字符串。
        /// </summary>
        internal static string DockerHost_21_Message {
            get {
                return ResourceManager.GetString("DockerHost.21.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A preexisting directory is not owned exclusively; cleanup is incomplete. 的本地化字符串。
        /// </summary>
        internal static string DockerHost_22_Message {
            get {
                return ResourceManager.GetString("DockerHost.22.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data ownership cannot be verified; cleanup is incomplete. 的本地化字符串。
        /// </summary>
        internal static string DockerHost_23_Message {
            get {
                return ResourceManager.GetString("DockerHost.23.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No managed release is available. 的本地化字符串。
        /// </summary>
        internal static string DockerHost_24_Message {
            get {
                return ResourceManager.GetString("DockerHost.24.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown component. 的本地化字符串。
        /// </summary>
        internal static string DockerHost_25_Message {
            get {
                return ResourceManager.GetString("DockerHost.25.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A nested mount prevents recursive cleanup. 的本地化字符串。
        /// </summary>
        internal static string DockerHost_26_Message {
            get {
                return ResourceManager.GetString("DockerHost.26.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} {1} failed (exit {2}); managed state was retained. 的本地化字符串。
        /// </summary>
        internal static string DockerHost_27_Message {
            get {
                return ResourceManager.GetString("DockerHost.27.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A system directory cannot be registered as application-owned data. 的本地化字符串。
        /// </summary>
        internal static string DockerHost_28_Message {
            get {
                return ResourceManager.GetString("DockerHost.28.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conflicting ownership requirements for a persistent directory. 的本地化字符串。
        /// </summary>
        internal static string DockerHost_29_Message {
            get {
                return ResourceManager.GetString("DockerHost.29.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The node architecture differs from the running executor. 的本地化字符串。
        /// </summary>
        internal static string DockerHost_3_Message {
            get {
                return ResourceManager.GetString("DockerHost.3.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Persistent directory ownership must be a numeric UID:GID. 的本地化字符串。
        /// </summary>
        internal static string DockerHost_30_Message {
            get {
                return ResourceManager.GetString("DockerHost.30.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A requested interface or host port is unavailable. 的本地化字符串。
        /// </summary>
        internal static string DockerHost_31_Message {
            get {
                return ResourceManager.GetString("DockerHost.31.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This bundle targets a different Linux distribution profile. 的本地化字符串。
        /// </summary>
        internal static string DockerHost_4_Message {
            get {
                return ResourceManager.GetString("DockerHost.4.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insufficient storage for managed assets and image staging. 的本地化字符串。
        /// </summary>
        internal static string DockerHost_5_Message {
            get {
                return ResourceManager.GetString("DockerHost.5.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An unknown global containerizer executable already exists; it was preserved. 的本地化字符串。
        /// </summary>
        internal static string DockerHost_6_Message {
            get {
                return ResourceManager.GetString("DockerHost.6.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The candidate executor cannot handle all retained application records. 的本地化字符串。
        /// </summary>
        internal static string DockerHost_7_Message {
            get {
                return ResourceManager.GetString("DockerHost.7.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The candidate executor protocol is incompatible. 的本地化字符串。
        /// </summary>
        internal static string DockerHost_8_Message {
            get {
                return ResourceManager.GetString("DockerHost.8.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The bootstrap package set is empty. 的本地化字符串。
        /// </summary>
        internal static string DockerHost_9_Message {
            get {
                return ResourceManager.GetString("DockerHost.9.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} {1} failed (exit {2}). Verify engine connectivity, source availability and target-platform support. 的本地化字符串。
        /// </summary>
        internal static string Engine_1_Message {
            get {
                return ResourceManager.GetString("Engine.1.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot resolve the image user. Declare numeric data-owner in the template. 的本地化字符串。
        /// </summary>
        internal static string Engine_10_Message {
            get {
                return ResourceManager.GetString("Engine.10.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No usable build engine and Compose provider were found. Ensure Docker or Podman is running and its Compose provider is installed. On Windows, check `podman machine list` and start the selected machine with `podman machine start`.
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string Engine_2_Message {
            get {
                return ResourceManager.GetString("Engine.2.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The acquired image does not match the fixed platform manifest digest. 的本地化字符串。
        /// </summary>
        internal static string Engine_3_Message {
            get {
                return ResourceManager.GetString("Engine.3.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The acquired image has the wrong platform. 的本地化字符串。
        /// </summary>
        internal static string Engine_4_Message {
            get {
                return ResourceManager.GetString("Engine.4.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The engine did not provide a verifiable registry manifest digest. 的本地化字符串。
        /// </summary>
        internal static string Engine_5_Message {
            get {
                return ResourceManager.GetString("Engine.5.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The image index must contain exactly one matching target platform. 的本地化字符串。
        /// </summary>
        internal static string Engine_7_Message {
            get {
                return ResourceManager.GetString("Engine.7.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid image reference. 的本地化字符串。
        /// </summary>
        internal static string Engine_8_Message {
            get {
                return ResourceManager.GetString("Engine.8.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A service needs an executable readiness check in its template or locked image. 的本地化字符串。
        /// </summary>
        internal static string Engine_9_Message {
            get {
                return ResourceManager.GetString("Engine.9.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation failed ({0}); inspect retained state. 的本地化字符串。
        /// </summary>
        internal static string Executor_Failure_Message {
            get {
                return ResourceManager.GetString("Executor.Failure.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interrupted; inspect status and use recover before resuming. 的本地化字符串。
        /// </summary>
        internal static string Executor_Interrupted_Message {
            get {
                return ResourceManager.GetString("Executor.Interrupted.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Empty JSON: {0} 的本地化字符串。
        /// </summary>
        internal static string Files_1_Message {
            get {
                return ResourceManager.GetString("Files.1.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsafe relative path: {0} 的本地化字符串。
        /// </summary>
        internal static string Files_2_Message {
            get {
                return ResourceManager.GetString("Files.2.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path escapes its root: {0} 的本地化字符串。
        /// </summary>
        internal static string Files_3_Message {
            get {
                return ResourceManager.GetString("Files.3.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Symbolic link/reparse point is not allowed: {0} 的本地化字符串。
        /// </summary>
        internal static string Files_4_Message {
            get {
                return ResourceManager.GetString("Files.4.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsupported or duplicate archive entry: {0} 的本地化字符串。
        /// </summary>
        internal static string Files_5_Message {
            get {
                return ResourceManager.GetString("Files.5.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Archive exceeds the extraction limit. 的本地化字符串。
        /// </summary>
        internal static string Files_6_Message {
            get {
                return ResourceManager.GetString("Files.6.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The application is not registered. 的本地化字符串。
        /// </summary>
        internal static string InstallationStore_1_Message {
            get {
                return ResourceManager.GetString("InstallationStore.1.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsupported or inconsistent installation record. 的本地化字符串。
        /// </summary>
        internal static string InstallationStore_2_Message {
            get {
                return ResourceManager.GetString("InstallationStore.2.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Another operation holds the application/host lock. 的本地化字符串。
        /// </summary>
        internal static string InstallationStore_3_Message {
            get {
                return ResourceManager.GetString("InstallationStore.3.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Managed release identity mismatch. 的本地化字符串。
        /// </summary>
        internal static string InstallationStore_4_Message {
            get {
                return ResourceManager.GetString("InstallationStore.4.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 --name differs from the bundle identity. 的本地化字符串。
        /// </summary>
        internal static string Lifecycle_1_Message {
            get {
                return ResourceManager.GetString("Lifecycle.1.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The original transaction assets changed. 的本地化字符串。
        /// </summary>
        internal static string Lifecycle_10_Message {
            get {
                return ResourceManager.GetString("Lifecycle.10.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 --retry-migration must select one failed/interrupted migration in this transaction. 的本地化字符串。
        /// </summary>
        internal static string Lifecycle_11_Message {
            get {
                return ResourceManager.GetString("Lifecycle.11.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The application is uninstalled; reinstall its retained bundle first. 的本地化字符串。
        /// </summary>
        internal static string Lifecycle_12_Message {
            get {
                return ResourceManager.GetString("Lifecycle.12.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The target transaction is not ReadyToStart. Prepare alone cannot authorize activation. 的本地化字符串。
        /// </summary>
        internal static string Lifecycle_13_Message {
            get {
                return ResourceManager.GetString("Lifecycle.13.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 restart cannot bypass maintenance or an uncommitted transaction. 的本地化字符串。
        /// </summary>
        internal static string Lifecycle_14_Message {
            get {
                return ResourceManager.GetString("Lifecycle.14.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specify a component belonging to this application; infrastructure-only deployments need an explicit target. 的本地化字符串。
        /// </summary>
        internal static string Lifecycle_15_Message {
            get {
                return ResourceManager.GetString("Lifecycle.15.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uninstall/cleanup is incomplete; retained state lists the remaining failure. 的本地化字符串。
        /// </summary>
        internal static string Lifecycle_16_Message {
            get {
                return ResourceManager.GetString("Lifecycle.16.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No committed release exists. 的本地化字符串。
        /// </summary>
        internal static string Lifecycle_17_Message {
            get {
                return ResourceManager.GetString("Lifecycle.17.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The upgrade changes the deployment identity or platform. 的本地化字符串。
        /// </summary>
        internal static string Lifecycle_18_Message {
            get {
                return ResourceManager.GetString("Lifecycle.18.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Infrastructure changes are not supported by application upgrades. 的本地化字符串。
        /// </summary>
        internal static string Lifecycle_19_Message {
            get {
                return ResourceManager.GetString("Lifecycle.19.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 --name differs from the launcher bundle identity. 的本地化字符串。
        /// </summary>
        internal static string Lifecycle_2_Message {
            get {
                return ResourceManager.GetString("Lifecycle.2.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The upgrade changes bootstrap dependencies. 的本地化字符串。
        /// </summary>
        internal static string Lifecycle_20_Message {
            get {
                return ResourceManager.GetString("Lifecycle.20.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid or cyclic local service dependency. 的本地化字符串。
        /// </summary>
        internal static string Lifecycle_21_Message {
            get {
                return ResourceManager.GetString("Lifecycle.21.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 upgrade requires an existing registration. 的本地化字符串。
        /// </summary>
        internal static string Lifecycle_3_Message {
            get {
                return ResourceManager.GetString("Lifecycle.3.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A different transaction is pending. Recover or finish it before selecting another bundle. 的本地化字符串。
        /// </summary>
        internal static string Lifecycle_4_Message {
            get {
                return ResourceManager.GetString("Lifecycle.4.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A failed transaction requires recover; install does not clear failure state. 的本地化字符串。
        /// </summary>
        internal static string Lifecycle_5_Message {
            get {
                return ResourceManager.GetString("Lifecycle.5.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Migration {0} requires explicit recovery; it was not rerun. 的本地化字符串。
        /// </summary>
        internal static string Lifecycle_6_Message {
            get {
                return ResourceManager.GetString("Lifecycle.6.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A previous migration success no longer passes the companion fingerprint check. 的本地化字符串。
        /// </summary>
        internal static string Lifecycle_7_Message {
            get {
                return ResourceManager.GetString("Lifecycle.7.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Migration {0} failed; handle partial execution before requesting an explicit retry. 的本地化字符串。
        /// </summary>
        internal static string Lifecycle_8_Message {
            get {
                return ResourceManager.GetString("Lifecycle.8.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no failed or interrupted transaction to recover. 的本地化字符串。
        /// </summary>
        internal static string Lifecycle_9_Message {
            get {
                return ResourceManager.GetString("Lifecycle.9.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recover {0}: target {1}, phase {2}. 的本地化字符串。
        /// </summary>
        internal static string Lifecycle_Recovery {
            get {
                return ResourceManager.GetString("Lifecycle.Recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 make requires exactly one .container input. 的本地化字符串。
        /// </summary>
        internal static string Make_Input {
            get {
                return ResourceManager.GetString("Make.Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 With a .container input, only version, source, output and engine options may override the manifest. 的本地化字符串。
        /// </summary>
        internal static string Make_Options {
            get {
                return ResourceManager.GetString("Make.Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A .container manifest must be the only positional input. 的本地化字符串。
        /// </summary>
        internal static string Manifest_1_Message {
            get {
                return ResourceManager.GetString("Manifest.1.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: invalid digest. 的本地化字符串。
        /// </summary>
        internal static string Manifest_10_Message {
            get {
                return ResourceManager.GetString("Manifest.10.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The nginx shorthand conflicts with an explicit component. 的本地化字符串。
        /// </summary>
        internal static string Manifest_11_Message {
            get {
                return ResourceManager.GetString("Manifest.11.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The existing manifest has different effective content: {0} 的本地化字符串。
        /// </summary>
        internal static string Manifest_12_Message {
            get {
                return ResourceManager.GetString("Manifest.12.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Variable evaluation failed: {0} ({1}). 的本地化字符串。
        /// </summary>
        internal static string Manifest_13_Message {
            get {
                return ResourceManager.GetString("Manifest.13.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Identity must contain letters, digits, &apos;.&apos;, &apos;_&apos; or &apos;-&apos; and must not contain traversal segments. 的本地化字符串。
        /// </summary>
        internal static string Manifest_14_Message {
            get {
                return ResourceManager.GetString("Manifest.14.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version must contain two to four numeric parts and must not be zero. 的本地化字符串。
        /// </summary>
        internal static string Manifest_15_Message {
            get {
                return ResourceManager.GetString("Manifest.15.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}({1},1): {2} 的本地化字符串。
        /// </summary>
        internal static string Manifest_16_Message {
            get {
                return ResourceManager.GetString("Manifest.16.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}({1},1): Invalid section. 的本地化字符串。
        /// </summary>
        internal static string Manifest_17_Message {
            get {
                return ResourceManager.GetString("Manifest.17.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}({1},1): Duplicate key: {2} 的本地化字符串。
        /// </summary>
        internal static string Manifest_18_Message {
            get {
                return ResourceManager.GetString("Manifest.18.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid or unvalidated Linux distribution profile. 的本地化字符串。
        /// </summary>
        internal static string Manifest_19_Message {
            get {
                return ResourceManager.GetString("Manifest.19.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source directory does not exist: {0} 的本地化字符串。
        /// </summary>
        internal static string Manifest_2_Message {
            get {
                return ResourceManager.GetString("Manifest.2.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsupported application dependence; use runtime constraints, nginx shorthand or template dependencies. 的本地化字符串。
        /// </summary>
        internal static string Manifest_20_Message {
            get {
                return ResourceManager.GetString("Manifest.20.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid architecture, imaging, bootstrap or engine. 的本地化字符串。
        /// </summary>
        internal static string Manifest_3_Message {
            get {
                return ResourceManager.GetString("Manifest.3.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This name/tag/version already has a release. Change version or output. 的本地化字符串。
        /// </summary>
        internal static string Manifest_4_Message {
            get {
                return ResourceManager.GetString("Manifest.4.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At least one component is required. 的本地化字符串。
        /// </summary>
        internal static string Manifest_5_Message {
            get {
                return ResourceManager.GetString("Manifest.5.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duplicate component: {0} 的本地化字符串。
        /// </summary>
        internal static string Manifest_6_Message {
            get {
                return ResourceManager.GetString("Manifest.6.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: {1} is not allowed for this component kind. 的本地化字符串。
        /// </summary>
        internal static string Manifest_8_Message {
            get {
                return ResourceManager.GetString("Manifest.8.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: package architecture does not match the node. 的本地化字符串。
        /// </summary>
        internal static string Manifest_9_Message {
            get {
                return ResourceManager.GetString("Manifest.9.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid environment variable name. 的本地化字符串。
        /// </summary>
        internal static string Manifest_EnvironmentName_Message {
            get {
                return ResourceManager.GetString("Manifest.EnvironmentName.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid or duplicate migration sequence. 的本地化字符串。
        /// </summary>
        internal static string Manifest_MigrationSequence_Message {
            get {
                return ResourceManager.GetString("Manifest.MigrationSequence.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nested component sections are not supported. 的本地化字符串。
        /// </summary>
        internal static string Manifest_NestedComponent_Message {
            get {
                return ResourceManager.GetString("Manifest.NestedComponent.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown component key: {0} 的本地化字符串。
        /// </summary>
        internal static string Manifest_UnknownComponentKey_Message {
            get {
                return ResourceManager.GetString("Manifest.UnknownComponentKey.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown root key: {0} 的本地化字符串。
        /// </summary>
        internal static string Manifest_UnknownRootKey_Message {
            get {
                return ResourceManager.GetString("Manifest.UnknownRootKey.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid migration artifact name: {0} 的本地化字符串。
        /// </summary>
        internal static string MigrationInput_1_Message {
            get {
                return ResourceManager.GetString("MigrationInput.1.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Migration versions must be unique, ascending and match the node architecture. 的本地化字符串。
        /// </summary>
        internal static string MigrationInput_2_Message {
            get {
                return ResourceManager.GetString("MigrationInput.2.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Migration archive and companion script are both required: {0} 的本地化字符串。
        /// </summary>
        internal static string MigrationInput_3_Message {
            get {
                return ResourceManager.GetString("MigrationInput.3.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Migration directory does not exist: {0} 的本地化字符串。
        /// </summary>
        internal static string MigrationInput_4_Message {
            get {
                return ResourceManager.GetString("MigrationInput.4.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing migration companion: {0} 的本地化字符串。
        /// </summary>
        internal static string MigrationInput_5_Message {
            get {
                return ResourceManager.GetString("MigrationInput.5.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple candidates require an interactive choice or an explicit manifest. 的本地化字符串。
        /// </summary>
        internal static string MigrationInput_6_Message {
            get {
                return ResourceManager.GetString("MigrationInput.6.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid selection. 的本地化字符串。
        /// </summary>
        internal static string MigrationInput_7_Message {
            get {
                return ResourceManager.GetString("MigrationInput.7.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No matching migrations were found; this build has no migrations. 的本地化字符串。
        /// </summary>
        internal static string MigrationInput_NoMigrations {
            get {
                return ResourceManager.GetString("MigrationInput.NoMigrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: required environment/setting {1} is missing. 的本地化字符串。
        /// </summary>
        internal static string NodeBuilder_1_Message {
            get {
                return ResourceManager.GetString("NodeBuilder.1.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple applications require an explicit Nginx routing configuration. 的本地化字符串。
        /// </summary>
        internal static string NodeBuilder_10_Message {
            get {
                return ResourceManager.GetString("NodeBuilder.10.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nginx shorthand requires one unambiguous application HTTP port or an explicit routing configuration. 的本地化字符串。
        /// </summary>
        internal static string NodeBuilder_11_Message {
            get {
                return ResourceManager.GetString("NodeBuilder.11.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid component imaging value. 的本地化字符串。
        /// </summary>
        internal static string NodeBuilder_2_Message {
            get {
                return ResourceManager.GetString("NodeBuilder.2.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The release was created by another build; existing output was preserved. 的本地化字符串。
        /// </summary>
        internal static string NodeBuilder_3_Message {
            get {
                return ResourceManager.GetString("NodeBuilder.3.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The bundled executor is not a matching Linux ELF binary. 的本地化字符串。
        /// </summary>
        internal static string NodeBuilder_4_Message {
            get {
                return ResourceManager.GetString("NodeBuilder.4.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Native AOT executor is missing. Publish the target RID before packaging this tool. 的本地化字符串。
        /// </summary>
        internal static string NodeBuilder_5_Message {
            get {
                return ResourceManager.GetString("NodeBuilder.5.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unresolved local dependency: {0} 的本地化字符串。
        /// </summary>
        internal static string NodeBuilder_6_Message {
            get {
                return ResourceManager.GetString("NodeBuilder.6.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Two services publish a conflicting host port. 的本地化字符串。
        /// </summary>
        internal static string NodeBuilder_7_Message {
            get {
                return ResourceManager.GetString("NodeBuilder.7.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local service dependency cycle. 的本地化字符串。
        /// </summary>
        internal static string NodeBuilder_8_Message {
            get {
                return ResourceManager.GetString("NodeBuilder.8.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A service cannot depend on a later installation phase. 的本地化字符串。
        /// </summary>
        internal static string NodeBuilder_9_Message {
            get {
                return ResourceManager.GetString("NodeBuilder.9.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot clean the temporary directory; remaining path: {0}. {1} 的本地化字符串。
        /// </summary>
        internal static string NodeBuilder_FailedBuild_Message {
            get {
                return ResourceManager.GetString("NodeBuilder.FailedBuild.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prepare image: {0} 的本地化字符串。
        /// </summary>
        internal static string NodeBuilder_PrepareImage {
            get {
                return ResourceManager.GetString("NodeBuilder.PrepareImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 # {0} {1}
        ///
        ///Target: {2}, {3}.
        ///
        ///Services: {4}.
        ///
        ///Migrations: {5}.
        ///
        ///1. Define cross-node order, remote readiness and downtime with the delivery owner.
        ///2. Verify the installation archive and run `containerizer prepare {6}.tar.gz --name {0}`.
        ///3. Stop affected application nodes with `containerizer stop --name {0}`.
        ///4. Install/upgrade with `--no-start` in the agreed migration order.
        ///5. After all migrations succeed, run `containerizer start --name {0}` on each node.
        ///
        ///Recovery never automatically reruns [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string NodeBuilder_Readme {
            get {
                return ResourceManager.GetString("NodeBuilder.Readme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resolve bootstrap dependency closure. 的本地化字符串。
        /// </summary>
        internal static string NodeBuilder_ResolveBootstrap {
            get {
                return ResourceManager.GetString("NodeBuilder.ResolveBootstrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resolve image: {0} 的本地化字符串。
        /// </summary>
        internal static string NodeBuilder_ResolveImage {
            get {
                return ResourceManager.GetString("NodeBuilder.ResolveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Package architecture mismatch: {0} 的本地化字符串。
        /// </summary>
        internal static string PackageReader_1_Message {
            get {
                return ResourceManager.GetString("PackageReader.1.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This package compression is not supported. Supply a packager-generated gzip Debian package. 的本地化字符串。
        /// </summary>
        internal static string PackageReader_10_Message {
            get {
                return ResourceManager.GetString("PackageReader.10.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debian control metadata is missing. 的本地化字符串。
        /// </summary>
        internal static string PackageReader_11_Message {
            get {
                return ResourceManager.GetString("PackageReader.11.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid RPM lead. 的本地化字符串。
        /// </summary>
        internal static string PackageReader_12_Message {
            get {
                return ResourceManager.GetString("PackageReader.12.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This RPM compression is not supported. Supply a packager-generated gzip RPM. 的本地化字符串。
        /// </summary>
        internal static string PackageReader_13_Message {
            get {
                return ResourceManager.GetString("PackageReader.13.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid RPM cpio entry. 的本地化字符串。
        /// </summary>
        internal static string PackageReader_14_Message {
            get {
                return ResourceManager.GetString("PackageReader.14.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid cpio filename length. 的本地化字符串。
        /// </summary>
        internal static string PackageReader_15_Message {
            get {
                return ResourceManager.GetString("PackageReader.15.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid RPM header. 的本地化字符串。
        /// </summary>
        internal static string PackageReader_16_Message {
            get {
                return ResourceManager.GetString("PackageReader.16.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RPM header exceeds limits. 的本地化字符串。
        /// </summary>
        internal static string PackageReader_17_Message {
            get {
                return ResourceManager.GetString("PackageReader.17.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid RPM string offset. 的本地化字符串。
        /// </summary>
        internal static string PackageReader_18_Message {
            get {
                return ResourceManager.GetString("PackageReader.18.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unterminated RPM string. 的本地化字符串。
        /// </summary>
        internal static string PackageReader_19_Message {
            get {
                return ResourceManager.GetString("PackageReader.19.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Package input does not exist: {0} 的本地化字符串。
        /// </summary>
        internal static string PackageReader_2_Message {
            get {
                return ResourceManager.GetString("PackageReader.2.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No matching installation package in {0} or its .packages directory. 的本地化字符串。
        /// </summary>
        internal static string PackageReader_3_Message {
            get {
                return ResourceManager.GetString("PackageReader.3.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Package does not exist: {0} 的本地化字符串。
        /// </summary>
        internal static string PackageReader_4_Message {
            get {
                return ResourceManager.GetString("PackageReader.4.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tar installation companion is missing: {0}.sh 的本地化字符串。
        /// </summary>
        internal static string PackageReader_5_Message {
            get {
                return ResourceManager.GetString("PackageReader.5.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected a .deb, .rpm or .tar.gz installation package. 的本地化字符串。
        /// </summary>
        internal static string PackageReader_6_Message {
            get {
                return ResourceManager.GetString("PackageReader.6.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing or unsupported package architecture: {0} 的本地化字符串。
        /// </summary>
        internal static string PackageReader_7_Message {
            get {
                return ResourceManager.GetString("PackageReader.7.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Debian ar header. 的本地化字符串。
        /// </summary>
        internal static string PackageReader_8_Message {
            get {
                return ResourceManager.GetString("PackageReader.8.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Debian ar entry. 的本地化字符串。
        /// </summary>
        internal static string PackageReader_9_Message {
            get {
                return ResourceManager.GetString("PackageReader.9.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Required executable is unavailable: {0} 的本地化字符串。
        /// </summary>
        internal static string ProcessRunner_1_Message {
            get {
                return ResourceManager.GetString("ProcessRunner.1.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select migration numbers separated by commas:  的本地化字符串。
        /// </summary>
        internal static string Selection_MigrationPrompt {
            get {
                return ResourceManager.GetString("Selection.MigrationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select one package number:  的本地化字符串。
        /// </summary>
        internal static string Selection_PackagePrompt {
            get {
                return ResourceManager.GetString("Selection.PackagePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An explicit supported template is required for {0}: {1} 的本地化字符串。
        /// </summary>
        internal static string ServiceSource_1_Message {
            get {
                return ResourceManager.GetString("ServiceSource.1.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command arguments must be strings. 的本地化字符串。
        /// </summary>
        internal static string ServiceSource_10_Message {
            get {
                return ResourceManager.GetString("ServiceSource.10.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected an absolute Linux path without traversal. 的本地化字符串。
        /// </summary>
        internal static string ServiceSource_11_Message {
            get {
                return ResourceManager.GetString("ServiceSource.11.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ports require [IPv4:]host:container[/tcp|udp]. 的本地化字符串。
        /// </summary>
        internal static string ServiceSource_12_Message {
            get {
                return ResourceManager.GetString("ServiceSource.12.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsupported template protocol version. 的本地化字符串。
        /// </summary>
        internal static string ServiceSource_13_Message {
            get {
                return ResourceManager.GetString("ServiceSource.13.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application configuration must come from its installation package. 的本地化字符串。
        /// </summary>
        internal static string ServiceSource_14_Message {
            get {
                return ResourceManager.GetString("ServiceSource.14.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: unknown template key {1}. 的本地化字符串。
        /// </summary>
        internal static string ServiceSource_2_Message {
            get {
                return ResourceManager.GetString("ServiceSource.2.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: template does not support the selected architecture. 的本地化字符串。
        /// </summary>
        internal static string ServiceSource_3_Message {
            get {
                return ResourceManager.GetString("ServiceSource.3.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown template setting field: {0} 的本地化字符串。
        /// </summary>
        internal static string ServiceSource_4_Message {
            get {
                return ResourceManager.GetString("ServiceSource.4.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: invalid value for {1}. 的本地化字符串。
        /// </summary>
        internal static string ServiceSource_5_Message {
            get {
                return ResourceManager.GetString("ServiceSource.5.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration file is missing: {0} 的本地化字符串。
        /// </summary>
        internal static string ServiceSource_6_Message {
            get {
                return ResourceManager.GetString("ServiceSource.6.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown template section: {0} 的本地化字符串。
        /// </summary>
        internal static string ServiceSource_7_Message {
            get {
                return ResourceManager.GetString("ServiceSource.7.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: unknown setting {1}. 的本地化字符串。
        /// </summary>
        internal static string ServiceSource_8_Message {
            get {
                return ResourceManager.GetString("ServiceSource.8.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tool template is missing: {0} 的本地化字符串。
        /// </summary>
        internal static string ServiceSource_9_Message {
            get {
                return ResourceManager.GetString("ServiceSource.9.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: conflicting settings and explicit environment entry {1}. 的本地化字符串。
        /// </summary>
        internal static string Settings_Conflict {
            get {
                return ResourceManager.GetString("Settings.Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid .settings file: {0}. Expected component sections containing tag, repository and settings. 的本地化字符串。
        /// </summary>
        internal static string Settings_File {
            get {
                return ResourceManager.GetString("Settings.File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid settings. Use name=value pairs separated by semicolons; quote values containing semicolons. 的本地化字符串。
        /// </summary>
        internal static string Settings_Invalid {
            get {
                return ResourceManager.GetString("Settings.Invalid", resourceCulture);
            }
        }
    }
}
