//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zongsoft.Tools.Deployer.Properties {
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zongsoft.Tools.Deployer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 A deployment is already running on this instance: {0} 的本地化字符串。
        /// </summary>
        internal static string Review_Busy {
            get {
                return ResourceManager.GetString("Review.Busy", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Conflicting deployment assets: {0} 的本地化字符串。
        /// </summary>
        internal static string Review_Conflict {
            get {
                return ResourceManager.GetString("Review.Conflict", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Deployment cycle or depth limit: {0} 的本地化字符串。
        /// </summary>
        internal static string Review_Cycle {
            get {
                return ResourceManager.GetString("Review.Cycle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Dependency constraints cannot be satisfied: {0} 的本地化字符串。
        /// </summary>
        internal static string Review_DependencyConflict {
            get {
                return ResourceManager.GetString("Review.DependencyConflict", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 {0}: {1} 的本地化字符串。
        /// </summary>
        internal static string Review_Failure {
            get {
                return ResourceManager.GetString("Review.Failure", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Invalid filter: {0} 的本地化字符串。
        /// </summary>
        internal static string Review_InvalidFilter {
            get {
                return ResourceManager.GetString("Review.InvalidFilter", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Invalid option {0}: {1} 的本地化字符串。
        /// </summary>
        internal static string Review_InvalidOption {
            get {
                return ResourceManager.GetString("Review.InvalidOption", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Linked path is not allowed: {0} 的本地化字符串。
        /// </summary>
        internal static string Review_LinkedPath {
            get {
                return ResourceManager.GetString("Review.LinkedPath", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Locked deployment differs: {0} 的本地化字符串。
        /// </summary>
        internal static string Review_Locked {
            get {
                return ResourceManager.GetString("Review.Locked", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 File or package not found: {0} 的本地化字符串。
        /// </summary>
        internal static string Review_Missing {
            get {
                return ResourceManager.GetString("Review.Missing", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Package is not available in offline cache: {0} 的本地化字符串。
        /// </summary>
        internal static string Review_Offline {
            get {
                return ResourceManager.GetString("Review.Offline", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Target {0} is outside deployment root {1}. 的本地化字符串。
        /// </summary>
        internal static string Review_OutsideRoot {
            get {
                return ResourceManager.GetString("Review.OutsideRoot", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 {0}: {1} -&gt; {2} 的本地化字符串。
        /// </summary>
        internal static string Review_Planned {
            get {
                return ResourceManager.GetString("Review.Planned", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Copied {0}, skipped {1}, deleted {2}, failed {3}. 的本地化字符串。
        /// </summary>
        internal static string Review_Summary {
            get {
                return ResourceManager.GetString("Review.Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Undefined variable: {0} 的本地化字符串。
        /// </summary>
        internal static string Review_UndefinedVariable {
            get {
                return ResourceManager.GetString("Review.UndefinedVariable", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Unknown resolver: {0} 的本地化字符串。
        /// </summary>
        internal static string Review_UnknownResolver {
            get {
                return ResourceManager.GetString("Review.UnknownResolver", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The embedded runtime graph is missing: {0}. 的本地化字符串。
        /// </summary>
        internal static string RuntimeGraphMissing_Message {
            get {
                return ResourceManager.GetString("RuntimeGraphMissing.Message", resourceCulture);
            }
        }
    }
}
